server:
  port: 80

  servlet:
    session:
      cookie:
        http-only: false
#  servlet:
#    context-path: /springboot

#  http2:
#    enabled: true
#  ssl:
#    key-store: classpath:xxxx.pfx
#    key-store-password: xxxx
#    keyStoreType: PKCS12

spring:
  application:
    name: north
  mvc:
    throw-exception-if-no-handler-found: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 1000MB
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/springboot
    username: postgres
    password: postgres
    hikari:
      read-only: false
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000
#  jackson:
#    defaultPropertyInclusion: non_null
#    deserialization:
#      FAIL_ON_UNKNOWN_PROPERTIES: false


north:
  token-key: accessToken
  shiro-filter:
    enable-redis: true
    global-session-timeout: 1800000 #30*60*1000
    filter-chain-definition-map: |
        /sys/login:anon,
        /sys/logout:anon,
        /sys/unlogin:anon,
        /sys/403:anon,
        /sys/getMenu:authc,
        /favicon.ico:anon,
        /public/*:anon,
        /admin/*:anon,
        /sys/**:anon,

mybatis-plus:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath*:mybatis/**/*Mapper.xml
  typeAliasesPackage: com.north.*.entity
  type-handlers-package: com.north.base.typehandler
  global-config:
    db-config:
      id-type: id_worker_str
