server:
  port: 8000
#  ssl:
#    key-store: classpath:keystore.p12
#    key-password: northzx
#    key-store-password: northzx
#    keyStoreType: PKCS12
#  servlet:
#    context-path: /springboot
  http2:
    enable: true


spring:
  application:
    name: authority
  datasource:
    druid:
      url: jdbc:postgresql://127.0.0.1:5432/springboot
      username: root
      password: root
  redis:
      database: 1
      host: 127.0.0.1
      port: 6379
      password:
      timeout: 5000

endpoints:
  shutdown:
    enabled: true
    sensitive: true
security:
  user:
    name: north
    password: north
management:
  context-path: /north-manange
  address: 127.0.0.1

north:
  shiro-filter:
    filter-chain-definition-map: |
        /sys/login:anon,
        /sys/logout:anon,
        /sys/unlogin:anon,
        /favicon.ico:anon,
        /druid/*:anon,
        /admin/*:authc,
        /sys/*:authc,

mybatis:
  config: classpath:mybatis-config.xml
  mapperLocations: classpath*:mybatis/**/*Mapper.xml