server:
  port: 80
  http2:
    enable: true
#  servlet:
#    context-path: /springboot
#  ssl:
#    key-store: classpath:keystore.p12
#    key-password: northzx
#    key-store-password: northzx
#    keyStoreType: PKCS12

spring:
  application:
    name: north
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/springboot
    username: postgres
    password: postgres
    hikari:
      read-only: false
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      client-id: north-client
    consumer:
      group-id: north
      enable-auto-commit: true
      auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

north:
  token-key: accessToken
  shiro-filter:
    filter-chain-definition-map: |
        /sys/login:anon,
        /sys/logout:anon,
        /sys/unlogin:anon,
        /favicon.ico:anon,
        /admin/*:anon,
        /sys/*:anon,

mybatis-plus:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath*:mybatis/**/*Mapper.xml
  typeAliasesPackage: com.north.*.entity
  type-handlers-package: com.north.base.typehandler
  global-config:
    db-config:
      id-type: id_worker_str
