server:
  port: 80
#  ssl:
#    key-store: classpath:keystore.p12
#    key-password: northzx
#    key-store-password: northzx
#    keyStoreType: PKCS12
#  servlet:
#    context-path: /springboot
  http2:
    enable: true
im:
#  enable: false
  port: 81
  name: north
spring:
  application:
    name: authority
  datasource:
    druid:
      url: jdbc:postgresql://127.0.0.1:5432/springboot
      username: root
      password: root
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      client-id: north-client
    consumer:
      group-id: north
      enable-auto-commit: true
      auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

north:
  token-key: accessToken
  shiro-filter:
    filter-chain-definition-map: |
        /*:anon,
        /sys/*:authc,
mybatis:
  config: classpath:mybatis-config.xml
  mapperLocations: classpath*:mybatis/**/*Mapper.xml
mybatis-plus:
  mapper-locations: classpath*:mybatis/**/*Mapper.xml
  typeAliasesPackage: com.north.*.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2