server:
  port: 8000
  ssl:
    key-store: classpath:keystore.p12
    key-password: northzx
    key-store-password: northzx
    keyStoreType: PKCS12
  servlet:
#    context-path: /springboot
  http2:
    enable: true


spring:
  application:
    name: authority
  datasource:
    druid:
      url: jdbc:postgresql://127.0.0.1:5432/springboot
      username: postgres
      password: 123456
  redis:
      database: 1
      host: 192.168.101.246
      port: 6379
      password: 123456
      timeout: 5000

north:
  shiro-filter:
    filter-chain-definition-map: |
        /sys/login:anon,
        /sys/logout:anon,
        /sys/unlogin:anon,
        /favicon.ico:anon,
        /druid/*:anon,
        /admin/*:authc,
        /**:authc,

mybatis:
  config: classpath:mybatis-config.xml
  mapperLocations: classpath*:mybatis/**/*Mapper.xml